server:
  port: 9999
  servlet:
    context-path: /yyzx #前后端交互的端口和路径

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 181233

  #springfox swagger不支持spring2.7以上的版本
  #springfox使用的匹配路径是基于ant_path_matcher的,而spring2.7是基于path_pattern_matcher的
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #配置日期和时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis-plus配置
#打印Mybatis的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper xml的映射位置
  mapper-locations: classpath:/mapper/*.xml
  #项目实体包的路径
  type-aliases-package: com.cqupt.pojo,com.cqupt.dto,com.cqupt.vo
